name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Show HTML file
        run: cat index.html

      - name: Success message
        run: echo "GitHub Actions is working 🎉"
